### ISSUE TITLE
Create Presentation Demo

### ISSUE THREAD

**Issue by PatrickRBailey** [Jopatron/CapstoneDesign#12]
TODO:
- [x] Create PowerPoint presentation outlining project
- [x] Decide who should speak on each slide
- [x] Client/Needs
- [x] Overview of Design
- [x] Assumptions/ Potential concerns

**Comment by aaronflager** [comment]
Client: current set-up, what problem we're solving for them, who we're working with

[Patrick]
# Keller Williams Reality
- Largest Real Estate Franchise in North America by Broker Count
- Family First Company
- Focused on training Brokers to help them become more successful

# The Problem
- Find a way to update a process that is currently being done on paper
- Keeping track of Broker training
- Update the Staff on the progress of new Brokers

**Comment by aaronflager** [comment]
Approach for solving client problem: driving goals (DRY, etc), application architecture (MVC), responsive design

[Josh]

**Comment by aaronflager** [comment]
Concerns: mass emailing, scalable/adaptability, security, performance if database expands, long-term maintenance, asp.net or visual studio changing and that causing problems (especially b/c dotnetcore is so new), guiding client to proper web hosting service

[Aaron]
