### ISSUE TITLE
Design Doc, Appendix A, Acronyms

### ISSUE THREAD

**Issue by aaronflager** [Jopatron/CapstoneDesign#26]
Make a table that can have acronyms added to it to be filled in as we go.

Currently only applying Acronyms. Could be expanded to abbreviations, terms, and definitions if needed.

**Comment by JGarnick** [comment]
html, jquery, css, C#, view, model, controller, json, get, post, async, ajax

**Comment by JGarnick** [comment]
ERD, class, relationship, inheritance

**Comment by PatrickRBailey** [comment]
I think this should be specific to Acronyms

**Comment by JGarnick** [comment]
ORM, IDE

**Comment by JGarnick** [comment]
DBMS

**Comment by aaronflager** [comment]
Can always add more acronyms if needed. So far everything we've written about has an acronym, and even a few extra acronyms we didn't directly use have been added.
